language: objective-c
osx_image: xcode7.3x
xcode_project: TravisGo/TravisGo.xcodeproj
xcode_scheme: TravisGo
before_script:
script:
notifications:
after_script:
after_success:
branches:
  only:
    - master
    - develop
