language: objective-c
osx_image: xcode7.3
xcode_project: Unity-iPhone.xcodeproj
xcode_scheme: Unity-iPhone
before_script:
script:
notifications:
after_script:
after_success:
branches:
  only:
    - master
    - develop
